apiVersion: v1
kind: Service
metadata:
  name: webapp-gitops
  namespace: default
spec:
  selector:
    app: webapp-gitops
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
